import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className='overscroll-none scroll-smooth h-[10000px]'>
            <body className={`${inter.className} overscroll-none scroll-auto bg-white text-black`}>
                {children}
            </body>
        </html>
    )
}
